In [30]:
import pandas as pd
import numpy as np
import os
import getpass
import random
import time

In [78]:
def list_files(files):
    """Accepts a list and returns a dictionary of each item in list with a numbered index (key) starting at 1"""

    dir_list = {0:'Exit'}
    file_count = 0
    for file in files:
        file_count +=1
        dir_list[file_count] = file  # assign a number to each item in the list starting with 1 
    return dir_list  # returns the dictionary of items in the list

def print_dict(dict_items):
    """Prints the key:value pairing in a dictionary"""

    for key, value in dict_items.items():
        print(key, ":", value)

def check_dict(dict_to_check, choice):
    """Checks if the input choice is a key in the provided dictionary
        and returns 'valid' if true, 'invalid' if false"""

    if choice in dict_to_check:
        key_exists = "valid"
    else:
        key_exists = "invalid"

    return key_exists

def error_message(invalid_choice):
    print(f"Your input of '{invalid_choice}' is not a valid choice.")

def validate_int(user_input):
    """Checks if user input is an int. If not returns 'is_not_int'"""

    try:
        int(user_choice)
    except ValueError:
        print(f"'{user_choice}' is not an integer.")
        return "is_not_int"

def file_message():
    message1 = {1:'Great choice', 2:'Yes', 3:'Right away', 4:'Beep Boop Boop'}
    message2 = {1:'Fetching', 2:'Opening', 3:'Gathering'}

    mess1 = message1[random.randint(1,4)]
    mess2 = message2[random.randint(1,3)]
    return (mess1,mess2)

def determine_ulimit_position(top_position):
    if top_position == "Upper Limit":
        return 0
    else:
        return 1

def target_test_keys(keys): 
    """Accepts a list of lists and returns a list of the first value from each list"""
    
    spec_keys = []
    for i in range(len(keys)):
        spec_keys.append(keys[i][0])
    return spec_keys

def get_target_columns(col_list, spec_keys):
    target_columns = []
    for i in range(len(col_list)):
        if col_list[i] in spec_keys:
            target_columns.append(col_list[i])
    return target_columns

In [ ]:
dirs = sorted(os.listdir('data'))
dir_list = list_files(dirs)  # returned dict of files in directory

print_dict(dir_list)
user_choice = input('Enter the number next to the file to open. (0 to exit): ')

int_check = validate_int(user_choice)
if int_check == "is_not_int":
    validate_choice = "invalid"
else:
    validate_choice = check_dict(dir_list, int(user_choice)) # check to see if user input is a key in the dictionary

while validate_choice == "invalid":
    error_message(user_choice)
    print_dict(dir_list)
    user_choice = input('Enter the number next to the file to open. (0 to exit): ')
    int_check = validate_int(user_choice)
    if int_check == "is_not_int":
        validate_choice = "invalid"
    else:
        validate_choice = check_dict(dir_list, int(user_choice)) # check to see if user input is a key in the dictionary

    if user_choice == 0:
        break
    

print(f"{user_choice} is a valid choice")

print(dir_list[int(user_choice)])

if int(user_choice) != 0:
    file_to_open = 'data/' + dir_list[int(user_choice)]
    df = pd.read_csv(file_to_open)


In [61]:
# Super easy no error path

dirs = sorted(os.listdir('data'))
dir_list = list_files(dirs)  # returned dict of files in directory

user_choice = 3

if int(user_choice) != 0:
    selected_file = dir_list[int(user_choice)]
    fill_messages = file_message()
    print(f"{fill_messages[0]}! {fill_messages[1]} {selected_file} now...")
    time.sleep(3)  # pause execution for message
    df_all_specs = pd.read_csv('specifications.csv').set_index('product')  # read all product specifications into a df
    file_to_open = 'data/' + selected_file
    df = pd.read_csv(file_to_open)
    # prod = dir_list[int(user_choice)].rstrip(".csv")  # assuming all file choices are CSV files
    prod = os.path.splitext(selected_file)[0]  # separate filename from extension 
    df_prod_specs = df_all_specs.iloc[lambda x: x.index == prod]  # filter specifications by product name from the selected file
    prod_target_keys = target_test_keys(df_prod_specs.values)  # creates a list of product test keys that are in specifications file
    target_columns = get_target_columns(df.columns, prod_target_keys)  # creates a list of column name values, from the selected file,  that match values in prod_target_keys list

    print()  # whitespace
    print(f"The specifications for {prod} are below:")
    print(prod_target_keys)
    print(target_columns)

Great choice! Gathering YL1.csv now...

The specifications for YL1 are below:
['MDL', 'MDA', 'MDB', 'TDL', 'TDA', 'TDB', 'STR']


In [90]:
new = df[target_columns]
newer = np.array(df[target_columns])
newest = df[target_columns].to_numpy(dtype=float)
print(new.head())
print(newer)
print(newest)
print(type(new))
print(type(newer))
print(type(newest))

    MDL   MDA   MDB   TDL   TDA   TDB    STR
0 -0.78  0.62 -0.58  0.00  0.10 -1.92   93.0
1 -1.19  1.02 -0.54 -0.04  0.22 -2.08   92.7
2 -1.35  1.24 -0.47  0.07  0.13 -2.34   90.8
3 -1.32  1.32 -0.11  0.08  0.43 -2.07   92.1
4  0.20 -0.20  0.20  0.10 -0.10  0.30  102.0
[[-7.80e-01  6.20e-01 -5.80e-01  0.00e+00  1.00e-01 -1.92e+00  9.30e+01]
 [-1.19e+00  1.02e+00 -5.40e-01 -4.00e-02  2.20e-01 -2.08e+00  9.27e+01]
 [-1.35e+00  1.24e+00 -4.70e-01  7.00e-02  1.30e-01 -2.34e+00  9.08e+01]
 [-1.32e+00  1.32e+00 -1.10e-01  8.00e-02  4.30e-01 -2.07e+00  9.21e+01]
 [ 2.00e-01 -2.00e-01  2.00e-01  1.00e-01 -1.00e-01  3.00e-01  1.02e+02]
 [-1.15e+00  1.12e+00 -1.80e-01  1.00e-01  4.50e-01 -2.18e+00  9.11e+01]
 [ 2.00e-01 -2.00e-01  2.00e-01  1.00e-01 -1.00e-01  3.00e-01  1.02e+02]
 [-1.24e+00  1.04e+00  2.20e-01 -1.70e-01  2.30e-01 -2.05e+00  9.45e+01]
 [-1.07e+00  1.15e+00 -4.00e-02 -1.90e-01  3.10e-01 -1.72e+00  9.51e+01]
 [-4.00e-02 -4.00e-02 -7.40e-01  0.00e+00 -2.00e-02 -1.01e+00  9.64e+01]]

In [ ]:
# need to compare np array vs spec

In [34]:
ry = np.array([4,5,6])
len(ry)

3

In [ ]:
def compare_vs_spec():
    pass

In [78]:
test_df = (df['MDL'] <= df_ul_specs[1]) & (df['MDL'] >= df_ll_specs[1])
test_df

0    False
1    False
2    False
3    False
4     True
5    False
6     True
7    False
8    False
9     True
Name: MDL, dtype: bool